/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedPollsIndexRouteImport } from './routes/_authed/polls/index'
import { Route as AuthedPollsPollIdRouteImport } from './routes/_authed/polls/$pollId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPollsIndexRoute = AuthedPollsIndexRouteImport.update({
  id: '/polls/',
  path: '/polls/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPollsPollIdRoute = AuthedPollsPollIdRouteImport.update({
  id: '/polls/$pollId',
  path: '/polls/$pollId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/admin': typeof AdminRoute
  '/polls/$pollId': typeof AuthedPollsPollIdRoute
  '/polls': typeof AuthedPollsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/admin': typeof AdminRoute
  '/polls/$pollId': typeof AuthedPollsPollIdRoute
  '/polls': typeof AuthedPollsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/admin': typeof AdminRoute
  '/_authed/polls/$pollId': typeof AuthedPollsPollIdRoute
  '/_authed/polls/': typeof AuthedPollsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/admin' | '/polls/$pollId' | '/polls'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/admin' | '/polls/$pollId' | '/polls'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/admin'
    | '/_authed/polls/$pollId'
    | '/_authed/polls/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AdminRoute: typeof AdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/polls/$pollId': {
      id: '/_authed/polls/$pollId'
      path: '/polls/$pollId'
      fullPath: '/polls/$pollId'
      preLoaderRoute: typeof AuthedPollsPollIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/polls/': {
      id: '/_authed/polls/'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof AuthedPollsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedPollsPollIdRoute: typeof AuthedPollsPollIdRoute
  AuthedPollsIndexRoute: typeof AuthedPollsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedPollsPollIdRoute: AuthedPollsPollIdRoute,
  AuthedPollsIndexRoute: AuthedPollsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AdminRoute: AdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
